spring:
  application:
  name: spring-mhha

  datasource:
    spring-mssql:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;encrypt=true;trustServerCertificate=true
      username: sa
      password: master

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: 12345678

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 12580
  shutdown: immediate

logging:
  level:
    web: trace
    org:
      springframework:
        web: trace